<?php

/**
 * @file
 * Contains gaya_editorial_video.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @author Sébastien Libbrecht <slibbrecht@gaya.fr>
 */
function gaya_editorial_video_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gaya_editorial_video module.
    case 'help.page.gaya_editorial_video':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Gaya Editorial Video') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess
 *
 * Add variables in twig
 *
 * - entity_id: The entity ID of the object
 * - entity_bundle: The bundle of the object
 * - name: The backoffice title
 * - field_ge_title: The title can be showed
 *
 * @author Sébastien Libbrecht <slibbrecht@gaya.fr>
 * @param $variables
 * @param $hook
 */
function gaya_editorial_video_preprocess(&$variables, $hook) {
  if ($hook == 'gaya_editorial_entity') {
    if ($variables['elements']['#gaya_editorial_entity']->bundle() == 'gaya_editorial_video') {
      $entity = $variables['elements']['#gaya_editorial_entity'];
      $variables['entity_id'] = $entity->id();
      $variables['entity_bundle'] = $entity->bundle();
      $variables['name'] = $entity->getName();
      $variables['field_ge_title'] = $entity->get('field_ge_title')->getValue();
      $variables['field_ge_video_autohide'] = $entity->get('field_ge_video_autohide')->getValue();
      $variables['field_ge_video_autoplay'] = $entity->get('field_ge_video_autoplay')->getValue();
      $variables['field_ge_video_modestbranding'] = $entity->get('field_ge_video_modestbranding')->getValue();
      $variables['field_ge_video_provider'] = $entity->get('field_ge_video_provider')->getValue();
      $variables['field_ge_video_id'] = $entity->get('field_ge_video_id')->getValue();
      $variables['field_ge_video_id'] = $entity->get('field_ge_video_id')->getValue();
      $variables['field_ge_video_height'] = $entity->get('field_ge_video_height')->getValue();
      $variables['field_ge_video_width'] = $entity->get('field_ge_video_width')->getValue();

      // Attach library youtube or dailymotion
      switch ($variables['field_ge_video_provider'][0]['value']) {
        case 'youtube' :
          $variables['#attached']['library'][] = 'gaya_editorial_video/youtube-default';
          break;
        case 'dailymotion' :
          $variables['#attached']['library'][] = 'gaya_editorial_video/dailymotion-default';
          break;
      }
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * @author Sébastien Libbrecht <slibbrecht@gaya.fr>
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 */
function gaya_editorial_video_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  if ($hook == 'gaya_editorial_entity') {
    if ($variables['elements']['#gaya_editorial_entity']->bundle() == 'gaya_editorial_video') {
      $suggestions[] = 'gaya_editorial_video';
      $suggestions[] = 'gaya_editorial_video__' . $variables['elements']['#gaya_editorial_entity']->id();
    }
  }
}

/**
 * Implements hook_theme
 *
 * --
 * @author Sébastien Libbrecht <slibbrecht@gaya.fr>
 */
function gaya_editorial_video_theme() {
  $theme = [];
  $theme['gaya_editorial_video'] = [
    'variables' => array(
      'entity_id' => '',
      'entity_bundle' => '',
      'name' => '',
      'field_ge_title' => '',
      'field_ge_video_autohide' => '',
      'field_ge_video_autoplay' => '',
      'field_ge_video_modestbranding' => '',
      'field_ge_video_provider' => '',
      'field_ge_video_id' => '',
    ),
    'template' => 'gaya_editorial_video',
  ];
  return $theme;
}