field.ge_imagesslideshow_configuration.style_name:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Default'
      mapping:
        style_name:
          type: string
          label: 'Picture'

field.ge_imagesslideshow_configuration.theme_style:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Default'
      mapping:
        theme_style:
          type: string
          label: 'Value'

field.ge_imagesslideshow_configuration.little_picture:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Default'
      mapping:
        little_picture:
          type: integer
          label: 'Value'


field.ge_imagesslideshow_configuration.style_name_little:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Default'
      mapping:
        style_name_little:
          type: string
          label: 'Value'

field.ge_imagesslideshow_configuration.autostart:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Default'
      mapping:
        autostart:
          type: integer
          label: 'Value'