gaya_editorial.gaya_editorial_entity_type.*:
  type: config_entity
  label: 'Gaya editorial entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
  locked: true