<?php

/**
 * @file
 * Contains gaya_editorial_picture.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gaya_editorial_picture_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gaya_editorial_picture module.
    case 'help.page.gaya_editorial_picture':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Gaya Editorial Picture') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function gaya_editorial_picture_theme() {
  return array(
    'image_ge_formatter' => array(
      'variables' => array('item' => NULL, 'item_attributes' => NULL, 'url' => NULL, 'image_style' => NULL),
      'file' => 'gaya_editorial_picture.field.inc',
    ),
  );
}